#!/bin/bash

# Load Modules################################################################
##                                                            ##
##                    Campus Cluster                          ##
##     Sample Hybrid MVAPICH2/OpenMP Job Batch Script         ##
##                                                            ##
## PBS Options                                                ##
##                                                            ##
##  option -l                                                 ##
##    walltime: maximum wall clock time (hh:mm:ss)            ##
##       nodes: number of 12-core(taub) nodes                 ##
##                        16-core(golub) nodes                ##
##                        20-core(golub) nodes                ##
##         ppn: cores per node to use (1 thru 12) on taub     ##
##                                    (1 thru 16) on golub    ##
##                                    (1 thru 20) on golub    ##
##                                                            ##
##  option -N                                                 ##
##    job name (default = name of script file)                ##
##                                                            ##
##  option -q                                                 ##
##    queue name ( -q name_of_queue )                         ##
##                                                            ##
##  option -o                                                 ##
##     filename for standard output at end of job             ##
##     (default = <job_name>.o<job_id>).  File is written to  ##
##     directory from which qsub was executed. Remove extra   ##
##     "##" from the PBS -o line if you want to name your     ##
##     own file.                                              ##
##                                                            ##
##  option -e                                                 ##
##     filename for standard error at end of job              ##
##     (default = <job_name>.e<job_id>).  File is written to  ##
##     directory from which qsub was executed. Remove extra   ##
##     "##" from the PBS -e line if you want to name your     ##
##     own file.                                              ##
##                                                            ##
##  option -j                                                 ##
##     Join the standard output and standard error streams    ##
##     of the job                                             ##
##     ( -j oe  merges stderr with stdout and generates a     ##
##              stdout file <job_name>.o<job_id>              ##
##       -j eo  merges stdout with stderr and generates a     ##
##              stderr file <job_name>.e<job_id>  )           ##
##                                                            ##
##  option -m                                                 ##
##     mail_options (email notifications)                     ##
##     The mail_options argument is a string which consists   ##
##     of either the single character "n", or one or more of  ##
##     the characters "a", "b", and "e".                      ##
##     ( -m a   Send mail when the job is aborted.            ##
##       -m be  Send mail when the job begins execution and   ##
##              when the job terminates.                      ##
##       -m n   Do not send mail.  )                          ##
##                                                            ##
################################################################
#
#PBS -l walltime=0:30:00
#PBS -l nodes=1:ppn=16
#PBS -N pipeline500S2
#PBS -q secondary
##PBS -j oe
###PBS -o pipeline.out
###PBS -e pipeline.err
#PBS -m be
#PBS -M subrahm2@illinois.edu
#
#####################################

module load java
module load python/2.7.8

# Change to the directory from which the batch job was submitted
cd $PBS_O_WORKDIR

DATA=100S1

# Hard code and store paths needed for script
OUTPUT_DIR_PREFIX=/home/subrahm2/scratch/output/${DATA}
mkdir -p ${OUTPUT_DIR_PREFIX}

PASTA_DIR=/home/subrahm2/project-cse/Research/programs/pasta-code/pasta

PAGAN_DIR=/home/subrahm2/project-cse/Research/programs/pagan/bin

SCRIPTS_DIR=/home/subrahm2/project-cse/Research/research_scripts

TEMP_RESULTS_DIR=/home/subrahm2/scratch/temp/${DATA}
mkdir -p ${TEMP_RESULTS_DIR}

INPUT_SEQ_PATH_PREFIX=/home/subrahm2/project-cse/Research/data/${DATA}

FAST_TREE_OUTPUT_PREFIX=/home/subrahm2/project-cse/Research/fast-tree-output
mkdir -p ${FAST_TREE_OUTPUT_PREFIX}

FAST_TREE_PREFIX=/home/subrahm2/project-cse/Research/programs
FINAL_OUTPUT_DIR=/home/subrahm2/scratch/final_output/${DATA}
mkdir -p ${FINAL_OUTPUT_DIR}
# Pasta-Prank Pipeline

for i in R10; do

	INPUT_SEQ=${INPUT_SEQ_PATH_PREFIX}/${i}/rose.aln.true.fasta

	mkdir -p ${OUTPUT_DIR_PREFIX}/${i}
	OUTPUT_DIR=${OUTPUT_DIR_PREFIX}/${i}

	#delete gaps in input sequence
	python ${SCRIPTS_DIR}/gap_deletion_script.py ${INPUT_SEQ} ${TEMP_RESULTS_DIR}/new_input

	PASTA_OUT=${OUTPUT_DIR_PREFIX}/${i}
	mkdir -p ${PASTA_OUT}
	mkdir -p ${PASTA_OUT}/true-tree-pasta
	#run pasta without a guide tree
	python ${PASTA_DIR}/run_pasta.py -i ${TEMP_RESULTS_DIR}/new_input --output-directory=${PASTA_OUT}

	#run pasta with the true tree as the guide tree
	python ${PASTA_DIR}/run_pasta.py -i ${TEMP_RESULTS_DIR}/new_input -t ${INPUT_SEQ_PATH_PREFIX}/${i}/rose.tt --output-directory=${PASTA_OUT}/true-tree-pasta --iter-limit=1

	# delete the branch lengths to prepare the pasta tree for pagan
	python ${SCRIPTS_DIR}/research_script/remove_node_labels.py --in ${PASTA_OUT}/pastajob.tre --out ${TEMP_RESULTS_DIR}/new_guide_tree

	PAGAN_OUT=${OUTPUT_DIR_PREFIX}/${i}/pagan_output
	mkdir -p ${PAGAN_OUT}

	# run pagan with the true tree as the guide tree
    ${PAGAN_DIR}/pagan -seqfile=${TEMP_RESULTS_DIR}/new_input -treefile=${INPUT_SEQ_PATH_PREFIX}/${i}/rose.tt > ${PAGAN_OUT}/pagan_aln_out_true_tree

	#run pagan with the pasta tree as the guide tree
	${PAGAN_DIR}/pagan -seqfile=${TEMP_RESULTS_DIR}/new_input -treefile=${TEMP_RESULTS_DIR}/new_guide_tree > ${PAGAN_OUT}/pagan_aln_out_with_tree

	# run pagan with no guide tree
	${PAGAN_DIR}/pagan -seqfile=${TEMP_RESULTS_DIR}/new_input > ${PAGAN_OUT}/pagan_aln_out_no_tree


	#run FastSP on the pagan-true-tree alignment
	mkdir -p ${FINAL_OUTPUT_DIR}/helpful_output/pagan-true-tree/FastSP_output
	java -jar ${FAST_TREE_PREFIX}/FastSP_1.6.0.jar -r ${INPUT_SEQ_PATH_PREFIX}/${i}/rose.aln.true.fasta -e ${PAGAN_OUT}/pagan_aln_out_true_tree.best.fas > ${FINAL_OUTPUT_DIR}/helpful_output/pagan-true-tree/FastSP_output/${i}.txt

	# run FastSP on the pasta-true-tree alignment
	 mkdir -p ${FINAL_OUTPUT_DIR}/helpful_output/pasta-true-tree/FastSP_output
	 java -jar ${FAST_TREE_PREFIX}/FastSP_1.6.0.jar -r ${INPUT_SEQ_PATH_PREFIX}/${i}/rose.aln.true.fasta -e ${PASTA_OUT}/true-tree-pasta/pastajob.marker001.new_input.aln > ${FINAL_OUTPUT_DIR}/helpful_output/pasta-true-tree/FastSP_output/${i}.txt

	# run FastSP on pagan-pasta-tree alignment
	mkdir -p ${FINAL_OUTPUT_DIR}/helpful_output/pasta-pagan/FastSP_output

	java -jar ${FAST_TREE_PREFIX}/FastSP_1.6.0.jar -r ${INPUT_SEQ_PATH_PREFIX}/${i}/rose.aln.true.fasta -e ${PAGAN_OUT}/pagan_aln_out_with_tree.best.fas > ${FINAL_OUTPUT_DIR}/helpful_output/pasta-pagan/FastSP_output/${i}.txt


	# run FastSP on pasta-no-tree alignment
	mkdir -p ${FINAL_OUTPUT_DIR}/helpful_output/pasta/FastSP_output

	java -jar ${FAST_TREE_PREFIX}/FastSP_1.6.0.jar -r ${INPUT_SEQ_PATH_PREFIX}/${i}/rose.aln.true.fasta -e ${PASTA_OUT}/pastajob.marker001.new_input.aln > ${FINAL_OUTPUT_DIR}/helpful_output/pasta/FastSP_output/${i}.txt

	# run FastSP on pagan-no-tree alignment
	mkdir -p ${FINAL_OUTPUT_DIR}/helpful_output/pagan/FastSP_output
	java -jar ${FAST_TREE_PREFIX}/FastSP_1.6.0.jar -r ${INPUT_SEQ_PATH_PREFIX}/${i}/rose.aln.true.fasta -e ${PAGAN_OUT}/pagan_aln_out_no_tree.best.fas > ${FINAL_OUTPUT_DIR}/helpful_output/pagan/FastSP_output/${i}.txt

done